### ISSUE TITLE
Move to Multiformats?

### ISSUE THREAD

**Issue by RichardLitt** [greglook/clj-multihash#5]
Hey @greglook!

Thanks so much for this. As you may know, we recently created the [Multiformats](//github.com/multiformats) organization to be a home for all of the multiformats - multiaddr, multihash, etc. Would you be interested in moving this repository to that organization? You would still have admin rights on the repository, but it would be a part of a wider organization. This would mean more relevant eyes on it (most likely) and better cross-repository issue tracking. We'd also add a line mentioning you as the original author, and of course your commits would stay the same. 

Of course, keeping it on your profile is also cool; we'll still link to this from the main multihash repository at github.com/multiformats/multihash.

Thanks for taking the time to read this. 👍 

Tracking issue, here: https://github.com/multiformats/multiformats/issues/4.

**Comment by greglook** [comment]
Hey @RichardLitt, let me read up on repository transfers first, but this seems reasonable to me as long as I'm still an admin. :)

**Comment by RichardLitt** [comment]
@greglook You'd still be an admin. I've just added you to the organization: if you transfer the repo, I will re-add you as an admin of the repository. So, you'll be all set. :)

**Comment by greglook** [comment]
Hmm, I get the following error: `You don’t have admin rights to multiformats`

**Comment by RichardLitt** [comment]
That is super strange; this has worked for other people who have transferred. Try transferring it to me, and I will transfer it over to multiformats, then add you as an admin again for this repo?

**Comment by greglook** [comment]
Think it worked this time!

**Comment by RichardLitt** [comment]
Sweet! You're an admin now. Will send a PR for the README soon.
